SELECT 
    p.product_id, 
    p.product_name, 
    p.brand_id, 
    p.brand_name, 
    r.author_id, 
    p.loves_count, 
    p.rating, 
    p.reviews, 
    p.size, 
    p.variation_value, 
    p.ingredients, 
    p.limited_edition, 
    p.new, 
    p.online_only, 
    p.sephora_exclusive, 
    p.highlights, 
    p.category, 
    p.child_count, 
    p.child_max_price, 
    p.child_min_price, 
    r.helpfulness, 
    r.total_feedback, 
    r.total_negative_feedback, 
    r.total_positive_feedback, 
    r.date, 
    r.skin_tone, 
    r.eye_color, 
    r.skin_type, 
    r.hair_color, 
    r.price_usd, 
    p.revenue 
FROM product_info AS p
LEFT JOIN reviews_info AS r
ON p.product_id = r.product_id;